init commit
epambrest/quiz pull request #10
Opened 2020-09-14 12:26 UTC by katyakopeyko

2020-09-16 09:05 UTC, ihar-mialik requested changes

2020-09-19 17:46 UTC, viktartse requested changes

2020-09-19 17:46 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        public IActionResult ShowQuestion(Guid id)
А что будет если от пользователя придет Id, которого нет в базе?

2020-09-19 17:46 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +            var answer = question.OptionList.FirstOrDefault(i => i.IsAnswer == true);
Поиск правильного ответа было бы хорошо унести в сам класс SingleSelectionQuestion. У него есть все, чтобы сделать эту работу. И тест на него будет легко написать - не надо никаких моков для этого.

2020-09-19 17:46 UTC, viktartse commented on src/Teams/Domain/SingleSelectionQuestion.cs
> +
Для списков хорошей практикой считается избегать слова List в имени. Лучше использовать множественную форму Options (https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members).

Коллекция с "private set" все равно не достаточно инкапсулирована. Любой может изменять ее значения, не уведомляя сам класс. Лучше использовать что-то вроде
```
        private List<QuestionOption> options;
        public IReadOnlyCollection<QuestionOption> Options => options.ToList();
```
EF Core умеет мапить на backing fields.

2020-09-19 17:46 UTC, viktartse commented on src/Teams/Views/SingleSelectionQuestion/ShowQuestion.cshtml
> +        <div id=@option.Id><label><input type="radio" id=@option.Id name="myradio" onchange="select()">@option.Text</label></div>
Может стоит использовать что-нибудь более говорящее чем myradio?

2020-09-19 17:46 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        public JsonResult FindAnswer(Guid idQuestion)
QuestionId звучит лучше чем IdQuestion

2020-09-19 17:46 UTC, viktartse commented on src/Teams/Views/SingleSelectionQuestion/ShowQuestion.cshtml
> +            url: "/SingleSelectionQuestion/FindAnswer",
Вместо ручного конструирования url лучше воспользоваться таким методом 
`url: "@Url.Action("FindAnswer", new { idQuestion = Model.Id})",`
Тогда и параметр data не нужен

2020-09-20 00:34 UTC, katyakopeyko commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        public IActionResult ShowQuestion(Guid id)
@viktartse , как будет правильнее это решить? Возвращается null который передается во view, этот null нужно обработать на самой странице и вывести что-то вроде "no content"?  Или может перенаправлять в другой контроллер для вывода Error view?

2020-09-20 05:47 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        public IActionResult ShowQuestion(Guid id)
Я бы из контроллера возвращал 404.
`if (question == null) return NotFound();`

2020-09-20 16:27 UTC, viktartse commented on src/Teams/Domain/QuestionOption.cs
> +    public class QuestionOption: Entity
Я бы еще переименовал QuestionOption в что-нибудь, что бы четко говорило, что это вариант ответа для SingleSelectionQuestion, а не для какого-то произвольного вопроса.

2020-09-21 20:05 UTC, katyakopeyko commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +            var question = DbContext.SingleSelectionQuestions.Include(q => q.OptionList)
@viktartse , какая сущность должна реализовывать этот интерфейс?

2020-09-21 21:10 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +            var question = DbContext.SingleSelectionQuestions.Include(q => q.OptionList)
Сорри, не дописал название интерфейса. ISingleSelectionQuestionRepository. Соответственно, новый класс SingleSelectionQuestionRepository, в котором можно инкапсулировать логику конструирования объекта (извлечения из базы) со всеми нужными инклудами.

2020-09-22 12:18 UTC, viktartse requested changes
Как по мне, выглядит неплохо. За исключением, возможно, лишнего атрибута. Единственное, я бы предложил добавить юнит тест на логику, вынесенную в доменный объект (GetRightAnswer()). Юнит тесты лучше помещать в отдельный проект. Его надо создать. Что-нибудь вроде Teams.Tests. Также стоит придерживаться той же структуры папок, что и в основном проекте. Сейчас в тренде xUnit для юнит тестов. Давайте использовать его.

2020-09-22 12:18 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        [Route("SingleSelectionQuestion/{id?}")]
А этот атрибут обязательный? Мне кажется, что и без него точно такой еж route должен срабатывать. Если необязательный, то лучше его удалить.

2020-09-22 13:41 UTC, ihar-mialik approved these changes

2020-09-22 16:37 UTC, katyakopeyko commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        [Route("SingleSelectionQuestion/{id?}")]
@viktartse У меня без атрибута не срабатывает, поэтому и добавила его

2020-09-22 17:51 UTC, viktartse commented on src/Teams/Controllers/SingleSelectionQuestionController.cs
> +        [Route("SingleSelectionQuestion/{id?}")]
Тогда, такой вариант был бы лучше [Route("[Controller]/{id?}")]. В случае переименования класса, адрес тоже поменяется вслед за новым именем.

2020-09-22 17:52 UTC, viktartse commented on src/Teams/Domain/ISingleSelectionQuestion.cs
> +}
Этот файл, похоже, не нужен

2020-09-22 19:26 UTC, katyakopeyko commented
> Как по мне, выглядит неплохо. За исключением, возможно, лишнего атрибута. Единственное, я бы предложил добавить юнит тест на логику, вынесенную в доменный объект (GetRightAnswer()). Юнит тесты лучше помещать в отдельный проект. Его надо создать. Что-нибудь вроде Teams.Tests. Также стоит придерживаться той же структуры папок, что и в основном проекте. Сейчас в тренде xUnit для юнит тестов. Давайте использовать его.

@viktartse Как нужно доставать этот объект в тестах? Через контекст БД? Нужно сделать стабы на IApplicationDbContext (или ISingleSelectionQuestionRepository)?

2020-09-22 19:45 UTC, viktartse commented
Если мы говорим о тестировании GetRightAnswer из SingleSelectionQuestion, то у этого класса нет никаких внешних зависимостей. Его не надо доставать из  бд. В тесте надо создать объект этого класса с помощью конструктора класса, добавить варианты ответа (понадобится дополнительный метод для этого. Сейчас возможность добавлять ответы не реализована), вызвать GetRightAnswer и убедиться, что метод действительно вернул правильный ответ.

2020-09-22 20:40 UTC, viktartse reviewed
Выглядит, хорошо. Но еще бы добавить тест на случай, когда правильный ответ запрашивается, а вариантов ответа нет вообще. И, наверное, стоит запретить добавлять список ответов в InitializeOptions (выбрасывать исключение ArgumentException), в котором нет правильного ответа, или в котором больше одного ответа, и тоже добавить тесты для InitializeOptions на эти случаи. И на этом будет все.

2020-09-22 21:24 UTC, katyakopeyko commented
> Выглядит, хорошо. Но еще бы добавить тест на случай, когда правильный ответ запрашивается, а вариантов ответа нет вообще. И, наверное, стоит запретить добавлять список ответов в InitializeOptions (выбрасывать исключение ArgumentException), в котором нет правильного ответа, или в котором больше одного правильного ответа, и тоже добавить тесты для InitializeOptions на эти случаи. И на этом будет все.

@viktartse Может, еще нужно в GetRightAnswer добавить логику на проверку? Чтобы и там выбрасывалось исключение, если количество правильных ответов не 1? Или все-таки просто на возвращаемый null проверить?

2020-09-22 22:00 UTC, viktartse commented
Я бы оставил как есть. Идеальный вариант был бы - это не позволять создавать вопрос без вариантов ответа (передавать их в конструкторе), но мне кажется, EF не может использовать конструктор с коллекцией

2020-09-23 06:24 UTC, viktartse approved these changes

2020-09-23 06:24 UTC, viktartse commented on Teams.Tests/Domain/SingleSelectionQuestionTests.cs
> +        public void GetRightAnswer_GetsZeroOptions_ArgumentException()
Название этого теста не слишком удачное, т.к. выбрасывания исключения здесь нет.

2020-09-23 08:38 UTC, katyakopeyko commented on Teams.Tests/Domain/SingleSelectionQuestionTests.cs
> +        public void GetRightAnswer_GetsZeroOptions_ArgumentException()
Да, случайно не заметила, уже исправила)

2020-09-23 12:42 UTC, merged