Просмотр и проверка вопроса открытого типа
epambrest/quiz pull request #15
Opened 2020-09-17 20:15 UTC by Alex731322

2020-09-20 07:20 UTC, viktartse requested changes
HomeController нам бы мог пригодиться для других целей. Это страница, куда пользователь попадает с самого начала, с которой начинается знакомство пользователя с системой. Например, мы могли бы показать пользователю какую-то информацию о приложении. И использование его для показа вопроса одного единственного типа кажется не совсем верным. Будет лучше перенести всю новую логику в отдельный, новый контроллер.

SingleSelectionQuestion - это класс для вопросов с одним правильным ответом из нескольких, MultipleAnswerQuestion - это класс для вопросов с несколькими правильными ответами.

Тебе для твоего типа вопросов нужен свой отдельный специализированный класс. Вроде OpenAnswerQuestion. Этот новый класс будет хранить и текст вопроса и текст правильного ответа.

В этом кусочке работы не надо предлагать пользователю выбрать, какой вопрос он хочет увидеть. Надо принять от пользователя Id в параметре запроса (https://localhost:44370/OpenAnswerQuestion/Id) и показать вопрос с этим id и пустое поле для ответа.

Заполнение SampleData можно использовать в таком виде локально, но коммитать не надо. Лучше создать sql script. который бы делал тоже самое и вкоммитать его в отдельную папку SqlScripts. Кому надо, тот сам его запустит. У @ihar-mialik  были свои соображения на этот счет. @ihar-mialik , sampleData в миграциях, в скрипте или вообще не надо?

У меня есть еще предложения по изменениям, но они могут стать неактуальными, после переделок. Поэтому я подожду, когда основные изменения будут сделаны.

2020-09-22 13:46 UTC, ihar-mialik commented
> HomeController нам бы мог пригодиться для других целей. Это страница, куда пользователь попадает с самого начала, с которой начинается знакомство пользователя с системой. Например, мы могли бы показать пользователю какую-то информацию о приложении. И использование его для показа вопроса одного единственного типа кажется не совсем верным. Будет лучше перенести всю новую логику в отдельный, новый контроллер.
> 
> SingleSelectionQuestion - это класс для вопросов с одним правильным ответом из нескольких, MultipleAnswerQuestion - это класс для вопросов с несколькими правильными ответами.
> 
> Тебе для твоего типа вопросов нужен свой отдельный специализированный класс. Вроде OpenAnswerQuestion. Этот новый класс будет хранить и текст вопроса и текст правильного ответа.
> 
> В этом кусочке работы не надо предлагать пользователю выбрать, какой вопрос он хочет увидеть. Надо принять от пользователя Id в параметре запроса (https://localhost:44370/OpenAnswerQuestion/Id) и показать вопрос с этим id и пустое поле для ответа.
> 
> Заполнение SampleData можно использовать в таком виде локально, но коммитать не надо. Лучше создать sql script. который бы делал тоже самое и вкоммитать его в отдельную папку SqlScripts. Кому надо, тот сам его запустит. У @ihar-mialik были свои соображения на этот счет. @ihar-mialik , sampleData в миграциях, в скрипте или вообще не надо?
> 
> У меня есть еще предложения по изменениям, но они могут стать неактуальными, после переделок. Поэтому я подожду, когда основные изменения будут сделаны.



> @ihar-mialik , sampleData в миграциях, в скрипте или вообще не надо?

Предлагаю в миграции пока sample не помещать, с sql скриптом в принципе тоже пока можно обождать. Главное, чтобы рабочий код не содержал стабов

2020-09-23 07:14 UTC, viktartse reviewed
Sql скрипт тоже надо назвать в соответствии с тем, что он делает. И создание таблицы в нем - лишнее. Если таблицы почему-то нет, значит у нас проблема в другом месте, в миграциях.

2020-09-23 07:14 UTC, viktartse commented on src/Teams/Data/Migrations/20200921211446_Initial.cs
> +    public partial class Initial : Migration
Миграцию лучше назвать в соответствии с тем, что она делает

2020-09-23 07:14 UTC, viktartse commented on src/Teams/Views/OpenAnswerQuestion/Question.cshtml
> +    <form method="get" action="/OpenAnswerQuestion/Answer">
Можно просто action="Answer"

2020-10-05 20:40 UTC, viktartse requested changes

2020-10-05 20:40 UTC, viktartse commented on src/Teams/Controllers/OpenAnswerQuestionController.cs
> +            ViewData["question"] = question.Text;
Если использовать этот словарик для передачи данных во view, то теряется информация о типах передаваемых данных. Лучше завести отдельную модельку

2020-10-05 20:40 UTC, viktartse commented on src/Teams/Controllers/OpenAnswerQuestionController.cs
> +            ViewData["color"] = question.CheckAnswer(answer);
Для методов, возвращающих boolean обычно использую стиль вопросов, когда это возможно. Сравни: 
String.IsNullOrEmpty. Что означает булевый color?

2020-10-05 20:40 UTC, viktartse commented on src/Teams/Domain/OpenAnswerQuestion.cs
> +            return false;
Можно было бы записать так: return answer == Answer.
И на метод доменного класса можно написать тесты. У нас в мастере уже есть проект для тестов. Можно домержить в свой бранч изменения из мастера и добавить тесты.

2020-10-05 20:40 UTC, viktartse commented on src/Teams/Views/OpenAnswerQuestion/Answer.cshtml
> +        <font color="#0026ff">
font - устаревший атрибут. Лучше воспользоваться css.

2020-10-05 20:40 UTC, viktartse commented on src/Teams/Views/OpenAnswerQuestion/Answer.cshtml
> +        }
Я бы предпочел решение без js, если без него можно обойтись. Может попробовать сделать как здесь?
https://stackoverflow.com/questions/6899294/multiple-css-classes-in-an-html-element-asp-net-mvc-3

2020-10-15 17:08 UTC, viktartse requested changes

2020-10-15 17:08 UTC, viktartse commented on src/Teams/Views/OpenAnswerQuestion/Answer.cshtml
> +    </style>
Лучше использовать имена классов, которые бы означали успех и провал, чем зеленый и красный. Если вдруг мы передумаем и решим поменяем цвета, то придется менять не только определение классов, но и их названия и места их использования. 

Определения классов ничем не отличаются - оба про зеленую рамку.

2020-10-15 17:08 UTC, viktartse commented on Teams.Tests/Domain/OpenAnswerQuestionTests.cs
> +        }
Этого одного теста недостаточно, чтобы проверить все случаи. При том же самом правильном ответе было бы правильно протестировать случаи " Eton", "Eton ", "  Eton   " и случай с неправильным ответом.

2020-10-20 18:32 UTC, viktartse reviewed
Выглядит неплохо. У меня осталось только два замечания: параметризация тестов и непонятно, почему оба стиля зеленые.

2020-10-20 18:32 UTC, viktartse commented on Teams.Tests/Domain/OpenAnswerQuestionTests.cs
> +        public void CheckAnswer_Return()
Этот тест лучше сделать параметризированным с помощью атрибутов Theory и InlineData.

2020-10-20 18:32 UTC, viktartse commented on src/Teams/Views/OpenAnswerQuestion/Answer.cshtml
> +            border: 3px solid green;
Оба стиля - зеленый цвет. Мне казалось, что fail должен быть красного. Или я чего-то не понимаю?

2020-10-21 20:28 UTC, viktartse approved these changes

2020-10-30 16:25 UTC, ihar-mialik approved these changes

2020-11-01 09:11 UTC, Alex731322 commented on src/Teams/Controllers/OpenAnswerQuestionController.cs
> +        static int idQuestion;
Изначально я думал, что пользователь будет вводить в строке маршрутизации натуральное число соответствующее номеру вопроса.

2020-11-02 21:43 UTC, merged