Beta version
epambrest/quiz pull request #16
Opened 2020-09-20 09:46 UTC by Wolodymyr01

2020-09-20 19:44 UTC, viktartse requested changes

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Domain/Entity.cs
> +        public Guid Id { get; set; } // return back to private set after tests
Забыто?

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +            if (a.Count == 0) throw new ApplicationException("A question must have possible answers");
Использование ApplicationException не рекомендуется.
https://stackoverflow.com/questions/5685923/what-is-applicationexception-for-in-net

В данном случае можно было бы выбросить ArgumentException.

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +        public readonly string text;
Text уже есть в базовом классе.

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +        public List<Answer> answers;
Коллекция answers не инкапсулирована. Любой может изменять ее значения, не уведомляя сам класс. Лучше использовать что-то вроде
```
        private List<Answer> answer;
        public IReadOnlyCollection<Answer> Answers => answer.ToList();
```
EF Core умеет мапить на backing fields.

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +        }
Доставать самого себя из базы не совсем то, что должен делать доменный объект. Лучше добавить какой-нибудь IMultipleAnswerQuestionReposotory с методом Get(id) и использовать его, чтобы вернуть сконструированный объект.

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Models/MAQuestionModel.cs
> +        public string ID { get; set; }
Id - вторая буква меленькая

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Views/Quiz/MAQForm.cshtml
> +        border-color: green;
Я не увидел зеленого цвета. Рамка серая.

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Views/Quiz/MAQForm.cshtml
> +    <input readonly name="Id" value="@Model.ID" />
Зачем показывать id пользователю?

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Views/Quiz/MAQForm.cshtml
> +                <label for="answer">@Model.Answers[i].text</label>
label не работает. После щелчка мышью по надписи флажок не проставляется

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Views/Quiz/MAQForm.cshtml
> +            var cnt = @Html.Raw(Json.Serialize(Model.Answers.Count));
Стоит придумать более говорящие имена вместо загадочных x, checks, cnt.

2020-09-20 19:44 UTC, viktartse commented on src/Teams/Views/Quiz/MAQForm.cshtml
> +    }
Мне кажется, что этот метод вполне может себе жить прямо в доменном объекте MultipleAnswerQuestion. Чем меньше кода во вью, тем лучше. И для идентификации ответов лучше не использовать их порядковый номер в списке ответов, а использовать их Id. При выборке из базы нет никаких гарантий, что там будет какой-то особый порядок, если только порядок не задан в самом запросе. И имя getRightAnswers лучше, чем имя getRightAns.

2020-10-12 20:29 UTC, viktartse requested changes

2020-10-12 20:29 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +        public string[] GetRightAnswers()
Метод не возвращает правильные ответы. Поэтому название вводит в заблуждении. Лучше его переименовать, чтобы он правильно отражал реальность.

И было бы хорошо написать на него тесты, как это сделано для вопроса с одиночным выбором, который уже в мастере.

2020-10-12 20:29 UTC, viktartse commented on src/Teams/Views/MultipleAnswerQuestion/MultipleAnswerQuestionForm.cshtml
> +            var divs = document.getElementsByName("div");
Лучше не выбирать все div в документе - легко зацепить что-нибудь лишнее. Лучше выбирать в какой-либо области, например внутри `<div id="main_tree">`. Правда название main_tree  как-то не отражает сути того, что внутри и лучше это div переименовать.

2020-10-12 20:29 UTC, viktartse commented on src/Teams/Views/MultipleAnswerQuestion/MultipleAnswerQuestionForm.cshtml
> +            }
На мой вкус этот фрагмент как-то тяжеловато читается. jquery позволяет писать более выразительно. Может попробовать переписать на его основе? Что-нибудь вроде такого:
```
$("#main_tree label").each(
    function(index, element) {console.log(element.id)}
);
```

Определение стилей прямо в коде усложняет его чтение, лучше использовать css класс, как это у тебя было задумано изначально. С классом у тебя не получилось из-за выбранного имени. В bootstrap, который есть в проекте, уже определен стиль с таким именем. Отсюда и серая рамка. Выбор более специфичного имени мог бы решить изначальную проблему.

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Views/MultipleAnswerQuestion/MultipleAnswerQuestionForm.cshtml
> +                });
Было бы хорошо выделить эту часть в отдельную функцию с говорящим именем, и вызвать эту функцию в обработчике. Нужно только для того, чтобы легче было понять, что собственно говоря этот код делает.

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Views/MultipleAnswerQuestion/MultipleAnswerQuestionForm.cshtml
> +                <label for="answer[@i]" id="@Answers[i].Id">@Answers[i].Text</label>
label for и input id все еще различаются. Поэтому клик по тексту не выделяет чекбох

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestionOption.cs
> +        public MultipleAnswerQuestionOption(string Text, bool IsRight = false)
Параметры методов должны начинаться с маленькой буквы

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +            if (text is null || text?.Length < 1) throw new ArgumentException("A question must have non-empty title");
Уже есть метод для этого string.IsNullOrEmpty

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +        List<MultipleAnswerQuestionOption> answers;
Лучше всегда использовать явный модификатор доступа (private)

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Controllers/MultipleAnswerQuestionController.cs
> +        [HttpPost]
А как открыть вопрос в браузере, если он только на post отзывается?

2020-10-19 19:40 UTC, viktartse commented on src/Teams/Controllers/MultipleAnswerQuestionController.cs
> +            questionRepository = new MultipleAnswerQuestionRepository(_db);
Не надо создавать MultipleAnswerQuestionRepository здесь. Надо его добавить в контейнер в Startup.cs. По аналогии с вопросом с одним правильным ответом

2020-10-19 19:40 UTC, viktartse commented on src/Teams.Tests/MultipleAnswerQuestionTests.cs
> +    public class MultipleAnswerQuestionTests
Лучше поддерживать туже структуру папок что и в основном проекте т.е. поместить в папку Domain.

2020-10-19 19:40 UTC, viktartse commented on src/Teams.Tests/MultipleAnswerQuestionTests.cs
> +    }
Метод, возвращающий ids, остался непротестированным

2020-10-21 13:13 UTC, Wolodymyr01 commented on src/Teams.Tests/MultipleAnswerQuestionTests.cs
> +    }
Вот насчёт этого будет вопрос. Чтобы протестировать этот метод, нужен вопрос, в котором присвоен id. Вручную из кода его присвоить нельзя. Остаётся только вариант обратиться к базе данных, где есть вопросы с уникальными id. Но мне кажется, что для теста это плохой вариант. Как тогда лучше поступить в этом случае?

2020-10-21 13:29 UTC, viktartse commented on src/Teams.Tests/MultipleAnswerQuestionTests.cs
> +    }
Согласен. Давай тогда проверим не сами id, а их количество.

2020-10-21 14:06 UTC, Wolodymyr01 commented on src/Teams.Tests/MultipleAnswerQuestionTests.cs
> +    }
Ок. Добавил, обновил ветку. Проверьте, пожалуйста, всё ли теперь правильно.

2020-10-21 14:16 UTC, viktartse approved these changes

2020-10-26 14:15 UTC, ihar-mialik approved these changes

2020-10-27 13:24 UTC, merged