Artsiom svirepa
epambrest/quiz pull request #22
Opened 2020-10-23 21:46 UTC by ShortQuality

Сделал все по заданию, но не смог корректно сделать миграцию, чтоб не создавалсь новая колонка в таблице Question.
Т.к проблема в конфигурировании корректной зависимости классов моделей Question, OpenAnswerQuestion и OpenAnswerQuestionModel. Так же буду ждать ваших комметариев, чтоб более корректно сделать и еще лучше понимать как лучше делать, и как не надо.

2020-10-27 18:57 UTC, viktartse requested changes
Мне кажется, что здесь слишком много функциональности. Просмотр списка вопросов, удаление, просмотр подробностей о вопросе - это скорее нужно будет не в рамках всех вопросов одного типа, а в рамках теста, который сможет комбинировать вопросы разных типов. Поэтому здесь я бы оставил только то, что относится к созданию и редактированию вопроса.

2020-10-27 18:57 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            if (id != null)
Может Guid быть равным null?

2020-10-27 18:57 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +                OpenAnswerQuestionModel ModelForView = new OpenAnswerQuestionModel { Question = question.Text, Answer = question.Answer.AnswerText, Id = question.Id };
Локальные переменные должны начинаться с маленькой буквы. Предпочтительный способ перечисления пропертей - в столбик - так легче читать.

2020-10-27 18:57 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +        public async Task<IActionResult> Create(OpenAnswerQuestionModel ModelForView)
Имена параметров - с маленькой буквы.

2020-10-27 18:57 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +                if (ModelForView != null)
Может в этом месте ModelForView быть null?

2020-10-27 18:57 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +                OpenAnswerQuestion question = await _db.OpenAnswerQuestions.Include(a => a.Answer).FirstOrDefaultAsync(p => p.Id == id);
Здесь question может быть null. Возможно стоит подстраховатаься?

2020-10-27 18:57 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            return RedirectToAction("Index");
А не работает просто достать вопрос из базы, обновить поля и сделать SaveChanges?

2020-10-29 08:04 UTC, ShortQuality commented on src/Teams/Domain/OpenAnswerQuestion.cs
> +        public OpenAnswerQuestionOption Answer { get; set; }
Но если будет просто поле string для ответа, то как и у Александра при создании миграции будет добавляться еще одна колонка в базу данных вопросов, в которой будут записаны тексты ответов. Но как я понял, мы должны иметь отдельные базы данных, которые содержат в себе текст ответа.

2020-10-29 08:05 UTC, ShortQuality commented on src/Teams/Startup.cs
> -using System;
Если вы про смену true на false, то это было в моем предыдущем задании.

2020-10-29 08:07 UTC, ShortQuality commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            return RedirectToAction("Index");
У меня не получилось, ибо уровень доступа к полю текста вопроса для изменения недоступен и у меня были проблемы при изменении полей непосредственно.

2020-10-29 08:20 UTC, viktartse commented on src/Teams/Domain/OpenAnswerQuestion.cs
> +        public OpenAnswerQuestionOption Answer { get; set; }
Да, будет дополнительная колонка. Это нормально.

2020-10-29 08:23 UTC, viktartse commented on src/Teams/Startup.cs
> -using System;
А почему тогда это изменение оказалось в пул-реквесте? Если оно уже смержено в master и и ты удалил свой старый бранч и создал новый из мастера, то в пул-реквест ничего такого попасть не должно.

2020-10-29 08:24 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            return RedirectToAction("Index");
Попробуй еще раз, когда Answer будет не отдельным классом а string.

2020-11-04 18:30 UTC, closed without merging