Creating and editing tests
epambrest/quiz pull request #24
Opened 2020-11-01 18:59 UTC by katyakopeyko

2020-11-11 17:40 UTC, viktartse requested changes

2020-11-11 17:40 UTC, viktartse commented on src/Teams/Data/TestRepos/TestRepository.cs
> +        public Test Get(Guid guid)
id было бы лучшим именем, чем guid

2020-11-11 17:40 UTC, viktartse commented on src/Teams/Data/QuestionRepos/QuestionRepository.cs
> +        public List<Question> GetTestQuestions(Guid id)
testId было бы лучшим именем, чем id. Глядя на имя метода не понятно, что за id имеется ввиду. Приходится смотреть на реализацию

2020-11-11 17:40 UTC, viktartse commented on src/Teams/Controllers/TestController.cs
> +            }
Опционально, но часто запись без циклов читается легче:
```
testDto.Questions = _questionRepository
                .GetTestQuestions(id)
                .Select(item => new QuestionDTO(item.Id, item.Text))
                .ToList();
```

2020-11-11 17:40 UTC, viktartse commented on src/Teams/Controllers/TestController.cs
> +                throw new ArgumentNullException();
В контроллере лучше не бросать исключение, а возвращать соответствующий HTTP статус return BadRequest()

2020-11-12 10:34 UTC, katyakopeyko commented on src/Teams/Views/Test/Edit.cshtml
> +<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
Да, я видела что она есть, но почему-то без этой строки не работает

2020-11-12 10:47 UTC, viktartse commented on src/Teams/Views/Test/Edit.cshtml
> +<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
Не работает потому, что вся вью рендерится на странице до того как библиотека подключается. Можешь в браузере открыть исходный код страницы и ты тоже это увидишь. Порядок рендеринга задается в  _Layout.cshtml. Если во вью использовать section Scripts и поместить скрипты туда, то они отрендерятся после после подключения библиотеки и будут работать.

2020-11-17 07:54 UTC, viktartse commented
А можно еще указать последовательность кликов, чтобы воспроизвести баг?

2020-11-17 09:57 UTC, katyakopeyko commented
> А можно еще указать последовательность кликов, чтобы воспроизвести баг?

На странице редактирования теста:
Если в списке несколько вопросов - удалить их (кнопка Delete справа вопроса). После удаления одного, следующие не удалятся.
Добавление вопросов в список - кнопка Add, далее submit в модальном окне. После этого кнопки Delete у вопросов не работают. Кнопка Add больше тоже не работает.

2020-11-17 17:17 UTC, viktartse commented
Ok. Я понял, что тут происходит. Сначала о причинах неработающих кнопок.
После перенесения скриптов в @section, они перестают рендерится внутри дива #page. Поэтому они не передобавляются на страницу (только то, что внутри #page передобавляется). Простой фикс - это по-другому назначать события. Они должны срабатывать не только для уже существующих элементов страницы, но и для новых (пусть и с тем же id, но новых). Например так: `$("#page").off().on('click', "#btnAddQuestions", function () {`
После этого существующие скрипты продолжат работать с новыми элементами страницы.

Теперь, почему мне кажется, что это решение (с возвращением самой страницы ей же) не очень элегантное.
Оно выглядит как попытка сделать form submit с помощью ajax. В ответ приходит вся страница. Пусть и используется только кусочек от нее - это неожиданно и запутывает. Я бы предложил здесь сделать обычный submit с обновлением всей страницы. Либо если хочется обновления только ее кусочка, то сделать это более явным и понятным: вынести ту часть разметки, которая обновляется в partial view и использовать эту partial view как на странице так и, чтобы вернуть из контроллера только то, что надо без необходимости потом вырезать кусок пришедшей страницы.

2020-11-18 16:57 UTC, katyakopeyko commented
> Ok. Я понял, что тут происходит. Сначала о причинах неработающих кнопок.
> После перенесения скриптов в @section, они перестают рендерится внутри дива #page. Поэтому они не передобавляются на страницу (только то, что внутри #page передобавляется). Простой фикс - это по-другому назначать события. Они должны срабатывать не только для уже существующих элементов страницы, но и для новых (пусть и с тем же id, но новых). Например так: `$("#page").off().on('click', "#btnAddQuestions", function () {`
> После этого существующие скрипты продолжат работать с новыми элементами страницы.
> 
> Теперь, почему мне кажется, что это решение (с возвращением самой страницы ей же) не очень элегантное.
> Оно выглядит как попытка сделать form submit с помощью ajax. В ответ приходит вся страница. Пусть и используется только кусочек от нее - это неожиданно и запутывает. Я бы предложил здесь сделать обычный submit с обновлением всей страницы. Либо если хочется обновления только ее кусочка, то сделать это более явным и понятным: вынести ту часть разметки, которая обновляется в partial view и использовать эту partial view как на странице так и, чтобы вернуть из контроллера только то, что надо без необходимости потом вырезать кусок пришедшей страницы.

Я хотела делать как обычный сабмит, но появился вопрос: как сделать несколько разных сабмитов на одну форму? Метод в контроллере (который post для этой страницы) обрабатывает сохранение теста в бд, а тут нужна разная логика для удаления и добавления вопросов, еще и так чтобы сабмит в итоге работал

2020-11-18 17:36 UTC, viktartse commented
Можно было бы сабмитать одну и туже форму, добавив hidden input, куда после нажатия на кнопку и перед сабмитом помещать значение, которое зависит от типа нажатой кнопки. На серверной стороне можно в зависимости от этого значения выполнить соответствующую логику.

Проблему с Partial не понял.

2020-11-22 19:03 UTC, viktartse approved these changes

2020-12-01 17:13 UTC, merged