Open AnswerQuestion Creating
epambrest/quiz pull request #25
Opened 2020-11-04 18:32 UTC by ShortQuality

Я решил создать новую ветку и удалить предыдущуюю, но предыдущий пул реквест был с той ветки и поэтому я его закрыл и создал новый пул реквест. Данное решение было принято после того, как Александр Данилюк смержил свой таск, чтоб я уже работал с его классом Открытого впороса

2020-11-08 20:39 UTC, viktartse requested changes

2020-11-08 20:39 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            OpenAnswerQuestion Question = new OpenAnswerQuestion(modelForView.Question, modelForView.Answer);
Имена локальных переменных должны начинаться с маленькой буквы.

2020-11-08 20:39 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            return RedirectToAction("Index");
А куда происходит этот переход?

2020-11-08 20:39 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            OpenAnswerQuestion Question = await _db.OpenAnswerQuestions.FirstOrDefaultAsync(p => p.Id == modelForView.Id);
Question -> question

2020-11-08 20:39 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            await _db.SaveChangesAsync();
При таком подходе меняется id вопроса. По сути, ты удаляешь старый вопрос и создаешь новый. И если на него будут ссылки, такое работать не будет. Лучше в класс OpenAnswerQuestion добавить метод, который обновит вопрос и ответ, тогда схема будет такая:
1. Достать вопрос из базы
2. Обновить его
3. Сохранить

2020-11-08 20:39 UTC, viktartse commented on src/Teams/Views/OpenQuestionCreate/Create.cshtml
> +        <label asp-for="Question" class="control-label">Question text</label>
Теоретически, текст вопроса может быть длинным, поэтому, лучше использовать поле с несколькими строками.

2020-11-08 20:39 UTC, viktartse commented on src/Teams/Views/OpenQuestionCreate/Create.cshtml
> +        <input type="submit" value="Submit" class="btn btn-default" />
btn-default отсутствует в используемой версии bootstrap.

2020-11-09 21:10 UTC, ShortQuality commented on src/Teams/Views/OpenQuestionCreate/Create.cshtml
> +        <label asp-for="Question" class="control-label">Question text</label>
А поле для текста ответа, так же сделать с несколькими строками или можно оставить и однострочный вариант?

2020-11-09 21:38 UTC, ShortQuality commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            await _db.SaveChangesAsync();
А почему нельзя оставить те же действия но в методе контроллера?

2020-11-10 07:41 UTC, viktartse commented on src/Teams/Views/OpenQuestionCreate/Create.cshtml
> +        <label asp-for="Question" class="control-label">Question text</label>
Для ответа хватит и однострочного поля

2020-11-11 12:16 UTC, viktartse requested changes

2020-11-11 12:16 UTC, viktartse commented on src/Teams/Domain/OpenAnswerQuestion.cs
> +        public void UpdateQuestion(OpenAnswerQuestionModel modelForView)
OpenAnswerQuestionModel - вот эти все модельки они только, чтобы данные гонять между view и контроллером. Не надо их использовать для передачи данных в доменный объект - плохой стиль. Обычно доменные объекты находятся в отдельном проекте (у нас сейчас это не так) и добавление ссылки на такую модельку ведет к добавлению ссылки на web проект, а домен ссылающийся на веб проект - вообще плохо. Лучше передавать две строки.

2020-11-11 12:16 UTC, viktartse commented on src/Teams/Domain/OpenAnswerQuestion.cs
> +        public void UpdateQuestion(OpenAnswerQuestionModel modelForView)
Ну, и раз есть метод, то давай еще напишем тест на него, проверяющий, что поля корректно обновились.

2020-11-11 18:01 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +            _db.Entry(question).State = EntityState.Modified;
Без этой строки не работает?

2020-11-11 19:39 UTC, viktartse requested changes

2020-11-11 19:39 UTC, viktartse commented on src/Teams.Tests/Domain/OpenAnswerQuestionUpdateTests.cs
> +        public void UpdateQuestion_return()
Непонятно, что означает return в названии.

2020-11-11 20:18 UTC, viktartse approved these changes

2020-11-13 13:15 UTC, ihar-mialik approved these changes

2020-11-16 22:30 UTC, merged