ProgramCodeQuestion and view
epambrest/quiz pull request #27
Opened 2020-11-06 18:08 UTC by Wolodymyr01

То, что было в задании, работает. Но post запрос к контроллеру не проходит. Но по заданию он пока не нужен, так что я его пока не трогал.

2020-11-08 20:59 UTC, viktartse requested changes

2020-11-08 20:59 UTC, viktartse commented on src/Teams/Views/ProgramCodeQuestion/Index.cshtml
> +                if (extension !== 'cs' && extension !== 'js') {
Проверки на тип файла и на его размер нужны и на бекэнде.

2020-11-08 20:59 UTC, viktartse commented on src/Teams/Views/ProgramCodeQuestion/Index.cshtml
> +                let extension = file.name.substring(file.name.indexOf('.') + 1)
А что если файл без расширения?

2020-11-08 20:59 UTC, viktartse commented on src/Teams/Views/ProgramCodeQuestion/Index.cshtml
> +            <input id="select_file" name="File" type="file" onchange="check_file()" />
По заданию, проверка должна осуществляться не при выборе файла, а при сабмите формы

2020-11-08 20:59 UTC, viktartse commented on src/Teams/Data/Repositories/ProgramCodeQuestionRepository.cs
> +        public void AddToDb(ProgramCodeQuestion question)
Давай пока не будем добавлять методы, которые нигде не используются

2020-11-08 20:59 UTC, viktartse commented on src/Teams/Domain/ProgramCodeQuestion.cs
> +        public IReadOnlyDictionary<string, string> InputsOutputsPairs => inputsOutputsPairs;
С этими словарями тоже непонятно, зачем они нужны. Если они не используются прямо сейчас, то давай не будем их добавлять

2020-11-09 16:05 UTC, Wolodymyr01 commented
Исправил и обновил. Но IIS Express на моменте post запроса просто обрывается и не грузит. При этом через browse with всё работает, как надо.

2020-11-09 19:05 UTC, viktartse requested changes

2020-11-10 20:09 UTC, viktartse requested changes

2020-11-10 20:09 UTC, viktartse commented on src/Teams/Models/ProgramCodeQuestionViewModel.cs
> +        public string AlertText { get; set; } = null;
А какое дефолтное значение у AlertText?

2020-11-10 20:09 UTC, viktartse commented on src/Teams/Controllers/ProgramCodeQuestionController.cs
> +            var extension_index = model.File.FileName.LastIndexOf('.');
extension_index тоже должен быть camelCase

2020-11-11 12:09 UTC, viktartse approved these changes

2020-11-13 13:14 UTC, ihar-mialik approved these changes

2020-11-13 13:24 UTC, merged