Creating Markdown
epambrest/quiz pull request #28
Opened 2020-11-17 16:58 UTC by Alex731322

2020-11-18 17:15 UTC, viktartse commented on src/Teams/Views/OpenAnswerQuestion/Answer.cshtml
> +    </markdown>
В таком виде оно не очень полезно. Это мы просто заменили один тег на другой хитрым способом.
Здесь нужно, чтобы текст который внутри Model.Question и который содержит markdown разметку, которую ввел пользователь, отображался с корректным форматированием.

2020-11-24 18:02 UTC, viktartse commented
Смотри, у нас уже есть контроллер OpenQuestionCreateController, который позволяет создавать вопросы открытого типа. Именно там у пользователя есть возможность ввести вопрос с markdown разметкой. В текущем пул-реквесте не надо дублировать эту функциональность. Нужно оставить только возможность отображать вопрос, который содержит текст с markdown.

2020-11-29 15:33 UTC, viktartse commented
Сейчас ты реализовал возможность для пользователя ввести вопрос c markdown разметкой и тут же на той же странице посмотреть, как он будет выглядеть. Хотя это может быть полезным, это все еще не то, что ожидается. 

Ожидается, что пользователь вводит вопрос с разметкой. Здесь никаких изменений не требуется.
Затем, когда пользователь открывает этот вопрос через https://localhost:44370/openanswerquestion/question/question_id, он видит этот вопрос отформатированный в соответствии с разметкой, которую он ввел. Только вопрос, варианты ответа все еще - plain text.

2020-11-30 09:51 UTC, Alex731322 commented
> Сейчас ты реализовал возможность для пользователя ввести вопрос c markdown разметкой и тут же на той же странице посмотреть, как он будет выглядеть. Хотя это может быть полезным, это все еще не то, что ожидается.
> 
> Ожидается, что пользователь вводит вопрос с разметкой. Здесь никаких изменений не требуется.
> Затем, когда пользователь открывает этот вопрос через https://localhost:44370/openanswerquestion/question/question_id, он видит этот вопрос отформатированный в соответствии с разметкой, которую он ввел. Только вопрос, варианты ответа все еще - plain text.

2020-11-30 10:14 UTC, Alex731322 commented
В таблице Questions содержится поле Text в которой записан сам вопрос на который нужно ответить, и есть поле TextAnswer который содержит правильный ответ, но у меня нет вариантов ответов. По какому пути мне пойти?
 1. Изменить базу данных добавив в нее варианты ответов
 2. Варианты ответов я могут хранится в  поле Text вместе с вопросом разделив их специальным символом например: &

2020-11-30 10:29 UTC, viktartse commented
Ну, если мы говорим о вопросе открытого типа, то у него нет вариантов ответа. Есть один правильный ответ, поэтому как-то модифицировать его с точки зрения добавления вариантов не нужно. У других типов вопросов могут быть варианты ответов, но их менять тоже не нужно. В рамках этого issue значение имеет только сам текст вопроса, который должен быть отрендерен как текст, который содержит markdown

2020-12-02 17:35 UTC, viktartse commented
Да, теперь вывод вопроса выглядит, как ожидалось.
Теперь давай применим его для всех типов вопросов, которые есть в мастере.

Поскольку ты решил сохранить предпросмотр разметки при создании вопроса, то давай сделаем его более подходящим для переиспользования и тоже применим во всех подходящих местах.
1. Нам не нужен рендеринг markdown в ответах - эту часть надо удалить
2. Я думаю о вынесении функциональности предпросмотра в отдельный mvc компонент. Который может выглядеть как кнопка, при нажатии на которую, на сервер посылается ajax запрос, сервер возвращает html с отрендеренным markdown, пользователю показывается окно с этим html. Это первое, что пришло в голову. Финальная версия может быть другой. Важно, чтобы можно было с минимальными усилиями добавить такую же функциональность во все места, где она может быть нужна.

2020-12-09 17:58 UTC, viktartse commented
1. Сразу после открытия страницы
https://localhost:44370/OpenQuestionCreate/Create

наблюдается вот такая ошибка в консоли браузера
![image](https://user-images.githubusercontent.com/1754953/101667502-763e5500-3a60-11eb-94ac-0974be668536.png)

2. Ответы все еще парсятся в предпросмотре. Нам это точно не надо.
3. Объясни, пожалуйста, если надо добавить такой же предпросмотр для другого типа вопроса, что надо будет поменять/добавить?

2020-12-09 19:41 UTC, Alex731322 commented
Посмотрите пожалуйста последний коммит, в связи с тем что я смержил ветку то первый коммит это изменения которые были после мержа, в коммите Fixed были добавлены именно мои изменения.

2020-12-09 20:14 UTC, viktartse commented
Да, не все изменения забрал. 

Меня смущают два момента:
1. Необходимость нажимать кнопку Назад в браузере, чтобы вернуться к вопросу после предпросмотра..
2. Передача текста вопроса c использованием GET в параметре запроса. Длина url сильно ограничена браузером и весь вопрос в нее может не поместиться.

Может все же стоит отсылать аяксом c помощью POST и показывать на результат на той же странице в диалоговом окне?

2020-12-15 16:50 UTC, viktartse requested changes
Еще обрати внимание на сообщения от самого гитхаба:
The using directive for 'Teams.Data.SingleSelectionQuestionRepos' appeared previously in this namespace

2020-12-15 16:50 UTC, viktartse commented on src/Teams/Controllers/OpenQuestionCreateController.cs
> +        public JsonResult GetMarkdownQuestion(string Quest)
Стоит вынести этот метод в отдельный контроллер. Теперь он не имеет никакого отношения к OpenQuestionCreateController

2020-12-15 16:50 UTC, viktartse commented on src/Teams/Views/OpenQuestionCreate/Create.cshtml
> +    function getMarkdownQuestion(quest) {
Этот js-код нужно добавлять в каждом месте, где нам нужен предпросмотр markdown? Нет ли способа избежать такой копипасты?

2020-12-15 16:50 UTC, viktartse commented on src/Teams/TagHelpers/MarkdownParserTagHelper.cs
> +                $"<input type=\"button\" value='Parse to Markdown' class='btn btn-light' onclick=\"getMarkdownQuestion(document.getElementById('questionInput').value)\"" +
Есть ли возможность параметризировать этот tag параметром questionInput? Иначе при добавлении тега в новое место придется менять названия инпутов для вопросов.

2020-12-18 14:45 UTC, viktartse reviewed
In general, looks good. There are just a couple of minor changes left.

2020-12-18 14:45 UTC, viktartse commented on src/Teams/ViewComponents/MarkdownScriptFormViewComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync(string questId)
Why it's async if there is no await?

2020-12-18 14:45 UTC, viktartse commented on src/Teams/ViewComponents/MarkdownScriptFormViewComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync(string questId)
The name questId is confusing. Quest is a separate word in English. it's better to use "question" instead of "quest".

2020-12-18 14:45 UTC, viktartse commented on src/Teams/Controllers/MarkParserController.cs
> +        public JsonResult GetMarkdownQuestion(string Quest)
Quest -> question

2020-12-18 14:45 UTC, viktartse commented on src/Teams/Views/Shared/Components/MarkdownScriptForm/Default.cshtml
> +<script src="~/lib/jquery/dist/jquery.js"></script>
The project already contains jquery. Take a look at  _Layout.cshtml

2020-12-18 14:45 UTC, viktartse commented on src/Teams/Views/Shared/Components/MarkdownScriptForm/Default.cshtml
> +        $.ajax({
Lack of indentation

2020-12-18 14:45 UTC, viktartse commented on src/Teams/Views/Shared/Components/MarkdownScriptForm/Default.cshtml
> +            success: function (owner) {
Why the name is "owner"?

2020-12-21 16:34 UTC, viktartse approved these changes

2020-12-23 11:01 UTC, viktartse commented
I've updated the requirements for merging. Now only one approval is required. You can merge your changes

2020-12-23 18:03 UTC, merged