Create multiple answer question
epambrest/quiz pull request #33
Opened 2020-11-27 11:48 UTC by IlyaPrikhach

Сделал вью для добавления вопросов в бд, и вью для редактирования вопроса из бд. Также контроллеры к ним. Использовал 2 метода отправки данных: form и ajax. Добавил метод MethodForAdd() в репозиторий и метод updateQuestion() в MultipleAnswerQuestion()

2020-11-29 15:07 UTC, viktartse requested changes

2020-11-29 15:07 UTC, viktartse commented on src/Teams/Controllers/MultipleAnswerQuestionController.cs
> +            for (int i = 0; i < fromAjax.jTextList.Length; i++)
Usually linq is easier to read. Could you try to replace the "for" loop with a linq and lambda expressions?

2020-11-29 15:07 UTC, viktartse commented on src/Teams/Controllers/MultipleAnswerQuestionController.cs
> +                // ChosenOptions = answers
Do we need this comment?

2020-11-29 15:07 UTC, viktartse commented on src/Teams/Controllers/MultipleAnswerQuestionController.cs
> +            int g = 0;
What is the meaning of the "g" variable. Could you use more meaningful names for variables?

2020-11-29 15:07 UTC, viktartse commented on src/Teams/Domain/MultipleAnswerQuestion.cs
> +        public void UpdateQuestion(string questionText, List<MultipleAnswerQuestionOption> Answers)
Answers -> answers

2020-11-29 15:07 UTC, viktartse commented on src/Teams/Controllers/MultipleAnswerQuestionController.cs
> +        }
I get an exception when I try to edit a question.
![image](https://user-images.githubusercontent.com/1754953/100545616-bede5d00-326d-11eb-8258-8f31f7bb0a72.png)

2020-12-05 15:54 UTC, IlyaPrikhach commented on src/Teams/Models/MAQDTOModel.cs
> +    public class MAQDTOModel  //Вот моя DTO модель
переименовал мою DTO-модель в MultipleAnswerQuestionDTOModel

2020-12-05 16:20 UTC, IlyaPrikhach commented on src/Teams/Models/MAQDTOModel.cs
> +        public bool[] jCheckboxList { get; set; }
Заменил jTextList и jCheckBoxList на TextMassive и CheckboxValueMassive соответственно. Написал "Massive", потому что в скрипте это может быть неочевидно.

2020-12-05 16:21 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +<meta charset="utf-8">
Я так понимаю что он не нужен? Убрал

2020-12-05 16:24 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +<label>Введите текст вопроса:</label>
Теперь это выглядит так <h3>Введите текст вопроса:</h3>

2020-12-05 16:24 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +<label>Введите текст вопроса:</label>
заменил label на h3

2020-12-05 16:34 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +         if(answersCount == 5 ){
Создал константу MaxAnswersNumber = 5; Именовал в PascalCase

2020-12-05 16:40 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +    <p id="hidenText" hidden>Добавьте текст ответа и отметьте правильный ли он</p>
В браузере вроде интуитивно понятно. Это сообщение появляется, когда нажимаешь на кнопку "Добавить"

2020-12-05 17:03 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +    function addForm() {
Заменил на AddAnswer()

2020-12-05 17:03 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +        }
Вроде исправил

2020-12-05 17:04 UTC, IlyaPrikhach commented on src/Teams/Views/MultipleAnswerQuestion/AddMultipleAnswerQuestion.cshtml
> +                console.log('Question is added');
Удалил

2020-12-06 13:10 UTC, viktartse commented
Have you pushed you changes?

2020-12-13 18:02 UTC, closed without merging