Added TestRun entity, Added Answer entity, created TestRun Controller.
epambrest/quiz pull request #37
Opened 2020-12-09 13:06 UTC by Razrmax

Created TestRun entity
Created Answer entity
Created TestRun controller

2020-12-10 21:36 UTC, viktartse commented
Открываю Testsruns/Index. Получаю такой exception:

![image](https://user-images.githubusercontent.com/1754953/101832347-4bc7c700-3b48-11eb-9ea8-c0a894aab29f.png)

Что-то недокомитано?

2020-12-13 12:32 UTC, viktartse commented
Сейчас солюшен не собирается:

![image](https://user-images.githubusercontent.com/1754953/102011934-71c3b600-3d58-11eb-9ce7-1432c58a49e5.png)

2020-12-13 20:44 UTC, Razrmax commented
> Сейчас солюшен не собирается:
> 
> ![image](https://user-images.githubusercontent.com/1754953/102011934-71c3b600-3d58-11eb-9ce7-1432c58a49e5.png)

Пофиксил, попробуйте теперь!

2020-12-14 20:48 UTC, viktartse requested changes

2020-12-14 20:48 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public List<string> AnswerText {get; private set;}
Почему решил сохранять строки? Вроде, собирались для вопросов, где есть id ответов, хранить эти id?
Как понять на какой вопрос эти ответы?

2020-12-14 20:48 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public Guid TestRunFK { get; set; }
Как будем использовать эти ссылки на TestRun? В каком из сценариев из issue они полезны?

2020-12-14 20:48 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +        public int AnswersCounter { get; set; }
Для чего нужно это свойство?

2020-12-14 20:48 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +        public Test Test {get; set;}
Давай не будем хранить ссылки на сущности Test и ApplicationUser. В твоем репозитории они не извлекаются, а если их начать извлекать, то при отсутствии lazy loading (а у нас оно выключено) может начать извлекаться много лишних данных. Достаточно сохранить TestId и TestedUserId

2020-12-14 20:48 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +}
Давай попробуем получить объект, который более похож на доменный и меньше похож на DTO. Сейчас все свойств доступны снаружи на чтение и на запись. Давай все же, как и планировали попробуем добавить методы для манипуляций и закроем все что возможно.

TestRun
    TestId
    UserId
    Collection Answers
        QuestionId
        Collection AnswerId
        AnswerText
    InProgress
    
    TestRun()
        Inprogress = true
        
    AddAnswer(anAnswer)
    
    Finish()
        InProgress = false

2020-12-14 20:51 UTC, viktartse commented
По поводу неработающих view. Если они не работают, то может и не стоит их добавлять? Особенно, если по заданию этого не требуется.

2020-12-18 16:41 UTC, viktartse requested changes

2020-12-18 16:41 UTC, viktartse commented on src/Teams/Domain/AnswerValue.cs
> +        public List<string> AnswerText { get; private set; }
private set - не делает поле безопасным для использования. Внешний код все еще может свободно добавлять и удалять элементы списка. Попробуй сделать его по-настоящему недоступным для изменения.

2020-12-18 16:41 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +        public bool InProgress { get; set; }
Давай все же сделаем это свойство доступным только для чтения. Иначе непонятно нужно ли его устанавливать в true при создании объекта. Ты и сам его где-то в коде устанавливаешь в true, хотя оно устанавливается в true в конструкторе.

А чтобы установить его в false давай введем метод Finish.

2020-12-18 16:41 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +        public List<Answer> Answers { get; private set; }
Этот список, несмотря на private set, торчит наружу всеми своими внутренностями и твой же код этим пользуется. Попробуй сделать его по-настоящему недоступным для изменения. А для добавления элементов стоит добавить отдельный метод AddAnswer.

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public Guid Id { get; }
А почему мы не можем наследоваться от Entity? Зачем изобретать Id?

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public Answer()
Можем ли сделать конструктор private? Он ведь нужен только для EF.

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public Answer(string answerText, List<Guid> answerIds, Guid testQuestionId, Guid id)
Почему для ответов мы задаем id, а для TestRun - нет?
Один ответ не может содержать и текст и id ответов. Конструктор с двумя опциями запутывает. Лучше сделать два конструктора: один с текстом, другой с answerIds

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +            foreach (var i in answerIds) _answerOptions.Add(i.ToString());
Тестировал этот фрагмент, когда список передается с элементами?
i - хорошо для счетчиков. Для foreach - это должно быть что-то более осмысленное. Например, id.

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public Guid TestQuestionId { get; }
Это поле не записывается в базу

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +        public TestRun(string testedUserId, Guid testId, List<Answer> answers)
Вряд ли нам будут известны ответы на момент создания сущности. Скорее будет необходимость добавлять из по одному после каждого пользовательского ответа. Лучше убрать answers из конструктора и добавить метод AddAnswer. который бы добавлял один ответ.

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/Answer.cs
> +        public IReadOnlyCollection<string> AnswerOptions => _answerOptions.AsReadOnly();
Можно изменить на IReadOnlyCollection<Guid> AnswerOptions ?

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Domain/TestRun.cs
> +        public Guid TestId { get; }
Есть ли возможность для всех свойств, которые не имеют backing field, использовать {get; private set;}, вместо `b.Property(e =>...` ?
Человеку, который захочет расширить класс и добавить новое свойство, будет сложно понять, почему он добавляет Prop {get; } как  у остальных свойств в классе, а значение не пишется в базу и не читается.

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Data/TestRunRepos/AnswerRepository.cs
> +    public class AnswerRepository : IAnswerRepository
Это репозиторий не имеет смысла. Ответы без самого TestRun не очень нужны. Его можно удалить.

2020-12-21 19:31 UTC, viktartse commented on src/Teams/Data/TestRunRepos/TestRunRepository.cs
> +    public class TestRunRepository : ITestRunRepository
Этот репозиторий возвращает не полностью сконструированные объекты. Answers - всегда null. Можно ли включить в результат и Answers?

2020-12-22 19:58 UTC, Razrmax commented on src/Teams/Domain/TestRun.cs
> +        public TestRun(string testedUserId, Guid testId, List<Answer> answers)
Для этого есть TestRunDTO, в который добавляются ответы по мере выполнения.

2020-12-22 19:59 UTC, Razrmax commented on src/Teams/Domain/Answer.cs
> +        public IReadOnlyCollection<string> AnswerOptions => _answerOptions.AsReadOnly();
Не совсем понимаю, а разве она не объявлена как IReadOnlyCollection?

2020-12-22 20:30 UTC, closed without merging